06_django_advanced/02_my_RECAP/classroom/urls.py
from django.urls import path
from . import views

app_name = 'classroom'

urlpatterns = [
    path('students/new', views.new, name='new'),
    path('students/create', views.create, name='create'),
    path('students/', views.list, name='list'),
    path('students/<int:id>', views.detail, name='detail'),
    path('students/<int:id>/edit', views.edit, name='edit'),
    path('students/<int:id>/update', views.update, name='update'),
    path('students/<int:id>/delete', views.delete, name='delete'),
]

06_django_advanced/02_my_RECAP/my_recap/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('classroom/', include('classroom.urls'))
]

06_django_advanced/02_my_RECAP/classroom/models.py
from django.db import models


class Student(models.Model):
    name = models.CharField(max_length=10)
    age = models.IntegerField()
    major = models.TextField()

06_django_advanced/02_my_RECAP/classroom/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST
from .models import Student


@require_GET
def new(request):
    return render(request, 'classroom/new.html')


@require_POST
def create(request):
    student = Student()
    student.name = request.POST.get('name')
    student.age = request.POST.get('age')
    student.major = request.POST.get('major')
    student.save()
    return redirect('classroom:detail', student.id)


@require_GET
def list(request):
    students = Student.objects.all()
    context = {'students': students}
    return render(request, 'classroom/list.html', context)


@require_GET
def detail(request, id):
    student = get_object_or_404(Student, id=id)
    context = {'student': student}
    return render(request, 'classroom/detail.html', context)


@require_GET
def edit(request, id):
    student = get_object_or_404(Student, id=id)
    context = {'student': student}
    return render(request, 'classroom/edit.html', context)


@require_POST
def update(request, id):
    student = get_object_or_404(Student, id=id)
    student.name = request.POST.get('name')
    student.age = request.POST.get('age')
    student.major = request.POST.get('major')
    student.save()
    return redirect('classroom:detail', student.id)


@require_POST
def delete(request, id):
    student = get_object_or_404(Student, id=id)
    student.delete()
    return redirect('classroom:list')

06_django_advanced/02_my_RECAP/classroom/templates/classroom/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}
    {% endblock title %}</title>
</head>
<body>
    {% block body %}
    {% endblock body %}
</body>
</html>

06_django_advanced/02_my_RECAP/classroom/templates/classroom/detail.html
{% extends 'classroom/base.html' %}

{% block title %}
Student Detail
{% endblock title %}

{% block body %}
    <h1>Name: {{ student.name }}</h1>
    <h2>Age: {{ student.age }}</h2>
    <h2>Major: {{ student.major }}</h2>
    <div>
        <a href="{% url 'classroom:edit' student.id %}"><button>Edit</button></a>
    </div>
    <div>
        <form action="{% url 'classroom:delete' student.id %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="Delete" onclick="return confirm('Really?')">
        </form>
    </div>
    <div>
        <a href="{% url 'classroom:list' %}"><button>Back to Board</button></a>
    </div>
{% endblock body %}

06_django_advanced/02_my_RECAP/classroom/templates/classroom/edit.html
{% extends 'classroom/base.html' %}

{% block title %}
Detail Edit
{% endblock title %}

{% block body %}
    <h1>Edit {{ student.name }}</h1>
    <form action="{% url 'classroom:update' student.id %}" method="POST">
        {% csrf_token %}
        <div>
            <label for="name">Name:</label>
            <input type="text" name="name" id="name" value='{{ student.name }}'>
        </div>
        <div>
            <label for="age">Age:</label>
            <input type="number" name="age" id="age" value='{{ student.age }}'>
        </div>
        <div>
            <label for="major">Major:</label>
            <input type="text" name="major" id="major" value='{{ student.major }}'>
        </div>
        <div>
            <input type="submit" value="Done">
        </div>
    </form>
{% endblock body %}

06_django_advanced/02_my_RECAP/classroom/templates/classroom/list.html
{% extends 'classroom/base.html' %}\

{% block title %}
Classroom Board
{% endblock title %}

{% block body %}
    <h1>SSAFY 2기 3반</h1>
    <ul>
    {% for student in students %}
    <ul>
        <a href="{% url 'classroom:detail' student.id %}">{{ student.name }}</a>
    </ul>
    {% endfor %}
    </ul>
    <div>
        <a href="{% url 'classroom:new' %}"><button>New Student</button></a>
    </div>
{% endblock body %}

06_django_advanced/02_my_RECAP/classroom/templates/classroom/new.html
{% extends 'classroom/base.html' %}

{% block title %}
New Student
{% endblock title %}

{% block body %}
    <form action="{% url 'classroom:create' %}" method="POST">
        {% csrf_token %}
        <div>
            <label for="name">Name:</label>
            <input type="text" name="name" id="name">
        </div>
        <div>
            <label for="age">Age:</label>
            <input type="number" name="age" id="age">
        </div>
        <div>
            <label for="major">Major:</label>
            <input type="text" name="major" id="major">
        </div>
        <div>
            <input type="submit" value="Register">
        </div>
    </form>
{% endblock body %}