06_django_advanced/01_django_RECAP/board/urls.py
from django.urls import path
from . import views

app_name = 'board'

urlpatterns = [
    # path('', views.index, name='index'),
    path('articles/', views.list_article, name='list_article'), # read 글 목록(list) render
    path('articles/<int:article_id>/', views.detail_article, name='detail_article'), # read 글 상세보기(detail) render
    path('articles/new/', views.new_article, name='new_article'), # create 글 쓰기(new) render
    # path('articles/create/', views.create, name='create'), # create 글 저장(create)
    path('articles/<int:article_id>/edit/', views.edit_article, name='edit_article'), # update 글 수정(edit) render
    # path('articles/<int:id>/update/', views.update, name='update'), # update 글 실제수정(update)
    path('articles/<int:article_id>/delete/', views.delete_article, name='delete_article'), # delete 글 삭제(delete)
    path('articles/<int:article_id>/comments/new/', views.new_comment, name='new_comment'),
    path('articles/<int:article_id>/comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
]

06_django_advanced/01_django_RECAP/django_recap/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls')),
    path('board/', include('board.urls')),
    path('poll/', include('poll.urls')),
]

06_django_advanced/01_django_RECAP/home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),  # HOST/home/
    path('guess/', views.guess, name='guess'),  # HOST/home/hi/
    path('answer/', views.answer, name='answer'),
]

06_django_advanced/01_django_RECAP/board/models.py
from django.db import models
from django.urls import reverse


class Article(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self): # detail page가 있을 때
        return reverse("board:detail_article", kwargs={"article_id": self.id})


class Comment(models.Model):
    content = models.CharField(max_length=200) # 200 넘어가면 알아서 자르고 저장
    # 폭포 처럼 ORIGINAL KEY(여기서는 CLASS ARTICLE)이 사라지면 여기서도 ARTICLE이 사라짐
    article = models.ForeignKey(Article, on_delete=models.CASCADE)

06_django_advanced/01_django_RECAP/board/forms.py
from django import forms
from .models import Article, Comment

# forms.Form => data 입력 및 검증
# forms.ModelForm => data 입력/검증 + HTML 생성

class ArticleForm(forms.Form):
    title = forms.CharField(min_length=2, max_length=100)
    content = forms.CharField()


class ArticleModelForm(forms.ModelForm):
    # 1. DATA 입력 및 검증
    # 2. HTML 생성

    title = forms.CharField(min_length=2, max_length=100)
    content = forms.Textarea
    class Meta:
        model = Article
        fields = '__all__'      # 모든 항목을 전부 검증

class CommentModelForm(forms.ModelForm):
    content = forms.CharField(min_length=2, max_length=200) # 200이 넘으면 아예 오류남

    class Meta:
        model = Comment
        fields = ('content',)   # content만 검증 // tuple, list 모두 가능한 syntax

06_django_advanced/01_django_RECAP/board/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_GET, require_POST, require_http_methods
from .models import Article, Comment
from IPython import embed
from .forms import ArticleModelForm, CommentModelForm


def new_article_with_form(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST)
        if form.is_valid():
            title = form.cleaned_data.get('title')
            content = form.cleaned_data.get('content')
            article = Article.objects.created(title=title, content=content)
            return redirect(article)
    else:
        form = ArticleForm()
    return render(request, 'board/new.html', {
        'form': form
    })

#CRUD
@require_http_methods(['GET', 'POST'])
def new_article(request):
    # 요청이 GET/POST 인지 확인한다.
    # 만약 POST 라면,
    if request.method == 'POST':
        form = ArticleModelForm(request.POST)
        # ArticleModelForm의 인스턴스를 생성하고 Data를 채운다.(binding).
        # binding 된 form이 유효한지 체크한다.
        if form.is_valid():
            # 유효하다면 저장한다.
            article = form.save()
            # 저장한 article 로 redirect 한다.
            # redirect('board:article_detail', article.id) => get_absolute_url 때문에 줄이기 가능
            return redirect(article)
        # form이 유효하지않다면,
        else:
            # 유효하지 않은 입력데이터를 담은 HTML과 에러메세지를 사용자한테 보여준다.
            return render(request, 'board/new.html', {
                'form': form,
            })
    # GET 이라면
    else:
        # 비어있는 form을 만든다.
        form = ArticleModelForm()
        # form 과 html을 사용자에게 보여준다.
        return render(request, 'board/new.html', {
            'form': form,
        })

def list_article(request):
    articles = Article.objects.all()
    context = {'articles': articles}
    return render(request, 'board/list.html', context)

def detail_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    comments = article.comment_set.all().order_by('-id')
    comment_form = CommentModelForm()
    context = {'article': article, 'comments': comments, 'comment_form': comment_form, }
    return render(request, 'board/detail.html', context)

@require_http_methods(['GET', 'POST'])
def edit_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    if request.method == 'POST':
        # update
        form = ArticleModelForm(request.POST, instance=article)
        if form.is_valid():
            article = form.save() # aritcle = 은 안 써도 된다
            return redirect(article)
    else:
        # edit
        # 그 article 내용을 가져올 수 있는 코드
        form = ArticleModelForm(instance=article)
    return render(request, 'board/edit.html', {'form': form})


@require_POST
def delete_article(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    article.delete()
    return redirect('board:list')


@require_POST
def new_comment(request, article_id):
    article = get_object_or_404(Article, id=article_id)
    form = CommentModelForm(request.POST)
    if form.is_valid():
        # comment = Comment()
        # comment.content = request.POST.get('content')
        comment = form.save(commit=False)
        comment.article_id = article.id
        comment.save()
    return redirect(article)


def delete_comment(request, article_id, comment_id):
    article = get_object_or_404(Article, id=article_id)
    # SELECT * FROM articles WHERE id=article_id
    comment = get_object_or_404(Comment, id=comment_id, article_id=article_id)
    # SELECT * FROM comments WHERE id=comment_id
    # if comment in article.comment_set.all():
    comment.delete()
    return redirect(comment.article)

06_django_advanced/01_django_RECAP/board/templates/board/_comment.html
<form action="{% url 'board:new_comment' article.id %}" method="post">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <input type="submit" value="submit">
</form>

{% if comments %}
    <ul>
        {% for comment in comments %}
            <li>{{ comment.content }}</li>
            <form action="{% url 'board:delete_comment' article.id comment.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="comment delete">
            </form>
        {% endfor %}
    </ul>
{% endif %}

06_django_advanced/01_django_RECAP/board/templates/board/_form.html
<form method="POST">
    {% csrf_token %}
    {{ form.as_table }}
    <input type="submit">
</form>

06_django_advanced/01_django_RECAP/board/templates/board/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>
    {% block body %}
    {% endblock body %}
</body>
</html>

06_django_advanced/01_django_RECAP/board/templates/board/detail.html
{% extends 'board/base.html' %}

{% block title %}
Article detail
{% endblock title %}

{% block body %}
    <h1>{{ article.title }}</h1>
    <p>
        created: {{ article.created_at }}
        <hr>
        updated: {{ article.updated_at }}
    </p>
    <p>
        {{ article.content }}
    </p>
    <div>
        <a href="{% url 'board:edit_article' article.id %}">
            <button>Edit</button>
        </a>
    </div>
    <div>
        <form action="{% url 'board:delete_article' article.id %}" method='POST'>
            {% csrf_token %}
            <input type="submit" id="delButton" value="delete">
        </form>
    </div>
    <script>
        const delButton = document.querySelector('#delButton');
        function popUp() {
            return confirm('really?')
        }
        delButton.addEventLister('click', popUp);
    </script>

    {% include 'board/_comment.html' %}

{% endblock body %}

06_django_advanced/01_django_RECAP/board/templates/board/edit.html
{% extends 'board/base.html' %}
{% block title %}
Edit Article
{% endblock title %}
{% block body %}
    {% include 'board/_form.html' %}
{% endblock body %}

06_django_advanced/01_django_RECAP/board/templates/board/index.html
{% extends 'board/base.html' %}

{% block title%}
{% endblock title %}

{% block body %}
Index
{% endblock body %}

06_django_advanced/01_django_RECAP/board/templates/board/list.html
{% extends 'board/base.html' %}

{% block title %}
    Article list
{% endblock title %}

{% block body %}
    <h1>This is Article list</h1>

    <a href="{% url 'board:new_article' %}"> New Article </a>

    {% if articles %}
        <ul>
            {% for article in articles %}
                <li>
                <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock body %}

06_django_advanced/01_django_RECAP/board/templates/board/new.html
{% extends 'board/base.html' %}
{% block title %}
{% endblock title %}
{% block body %}
    <h1>New Article</h1>
    {% include 'board/_form.html' %}
{% endblock body %}