06_django_advanced/03_image_upload/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('logout/', views.logout, name="logout"),
]

06_django_advanced/03_image_upload/image_uplaod/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings # MASTER_APP/settings.py

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('sns.urls')),
    # path('media', '/media/')
    path('accounts/', include('accounts.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

06_django_advanced/03_image_upload/sns/urls.py
from django.urls import path
from . import views

app_name = 'sns'

urlpatterns = [
    path('newsfeed/', views.posting_list, name='posting_list'),
    path('postings/<int:posting_id>/', views.posting_detail, name='posting_detail'),
    path('postings/create/', views.create_posting, name='create_posting'),
    path('<int:posting_id>/delete/', views.delete_posting, name='delete_posting'),
    path('postings/<int:posting_id>/comment/', views.create_comment, name='create_comment'),
    path('<int:posting_id>/comment/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('<int:posting_id>/toggle_like/', views.toggle_like, name='toggle_like'),
]

06_django_advanced/03_image_upload/sns/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
from faker import Faker

f = Faker()

# 지우고 싶을때
"""
$ python manage.py migrate <APP_NAME> zero  => unapplying all migrations
$ rm <APP_NAME>/migrations/0* => deleting all migrations files except __init__.py (all migrations files starting with 0)
"""


class Posting(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_postings', blank=True)
    content = models.TextField()
    icon = models.CharField(max_length=30, default='')
    image = models.ImageField(blank=True)  # 반드시 pip install Pillow 
    created_at = models.DateTimeField(auto_now_add=True)
    # auto now add 는 추가되었을 때, 생성 되었을 때 시간을 잼
    updated_at = models.DateTimeField(auto_now=True)
    # 수정 세이브 될 때 마다 시간을 잼

    class Meta:
        ordering = ['-created_at',] # created_at을 내림차순으로 정렬

    # detail 페이지를 쓸 거라면 만들어요
    def get_absolute_url(self):
        return reverse("sns:posting_detail", kwargs={"posting_id": self.id})

    def __str__(self):
        return f'{self.id}: {self.content[:10]}'

    @classmethod
    def dummy(cls, n):
        for _ in range(n):
            cls.objects.create(
                user_id=1,
                content=f.sentence(),
                icon='fas fa-angrycreative',
            )


class Comment(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # related_name 이 없으면, posting.comment_set / 아래와 같다면, posting.comments
    posting = models.ForeignKey(Posting, on_delete=models.CASCADE, related_name='comments')
    content = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['created_at',]

    def __str__(self):
        return f'{self.id}: {self.content[:10]}'


    @classmethod
    def dummy(cls, n, posting_id):
        for _ in range(n):
            cls.objects.create(
                user_id=1,
                posting_id=posting_id,
                content=f.sentence(),
            )

06_django_advanced/03_image_upload/sns/forms.py
from django import forms
from .models import Posting, Comment


class PostingModelForm(forms.ModelForm):
    content = forms.CharField(min_length=2)

    class Meta:
        model = Posting
        fields = ('content', 'image', 'icon',)


class CommentModelForm(forms.ModelForm):
    content = forms.CharField(min_length=2, max_length=200)

    class Meta:
        model = Comment
        fields = ('content',)

06_django_advanced/03_image_upload/sns/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_http_methods, require_GET, require_POST
from django.contrib.auth.decorators import login_required

from .models import Posting, Comment
from .forms import PostingModelForm, CommentModelForm


@require_GET
def posting_list(request):
    # nickname = request.COOKIES.get('nickname')
    postings = Posting.objects.all()
    context = {'postings': postings}
    return render(request, 'sns/posting_list.html', context)


@login_required # login이 안되면 => 무조건 /accounts/login/ 으로 보냄
@require_GET
def posting_detail(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    comments = posting.comments.all() # comment_set이 아닌 이유는 related_name이 comments이기 때문이다
    if posting.like_users.filter(id=request.user.id).exists():
        is_like = True
    else:
        is_like = False
    context = {'posting': posting, 'comments': comments, 'is_like': is_like}
    return render(request, 'sns/posting_detail.html', context)


@login_required # login이 안되면 => 무조건 /accounts/login/ 으로 보냄
@require_POST
def create_posting(request):
    form = PostingModelForm(request.POST, request.FILES)   # 검증 & 저장 준비
    if form.is_valid(): # 검증
        posting = form.save(commit=False) # 저장 후 posting 개체를 return
        # posting.user = request.user
        posting.user_id = request.user.id
        posting.save()
        return redirect(posting)
    else:
        return redirect('sns:posting_list')


@login_required # login이 안되면 => 무조건 /accounts/login/ 으로 보냄
@require_POST
def delete_posting(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    if request.user == posting.user:
        posting.delete()
    return redirect('sns:posting_list')


@login_required # login이 안되면 => 무조건 /accounts/login/ 으로 보냄
@require_POST
def create_comment(request, posting_id):
    posting = get_object_or_404(Posting, id=posting_id)
    form = CommentModelForm(request.POST) # content 만을 확인 (forms.py에 있는 fields만 읽는다)
    if form.is_valid():
        comment = form.save(commit=False)
        # comment.posting_id = posting_id
        comment.posting = posting
        comment.user = request.user
        comment.save()
    return redirect(posting)


@login_required # login이 안되면 => 무조건 /accounts/login/ 으로 보냄
@require_GET
def delete_comment(request, posting_id, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    comment.delete()
    return redirect(comment.posting)


@login_required
@require_POST
def toggle_like(request, posting_id):
    user = request.user
    posting = get_object_or_404(Posting, id=posting_id)
    if user in posting.like_users.filter(id=user.id).exists():
        posting.like_users.remove(user)
    else:
        posting.like_users.add(user)
    return redirect(posting)

# @require_POST
# def create_posting(request):
    # posting = Posting()
    # posting.content = request.POST.get('content')
    # posting.icon = ''
    # posting.image = request.FILES.get('image')
    # posting.save()
    # return redirect(posting)

06_django_advanced/03_image_upload/sns/templates/sns/_card.html
<article class="card mb-3">
    <a href="{{ posting.get_absolute_url }}">
    {% if posting.image %}
        <img src="{{ posting.image.url }}" alt="{{ posting.image }}"
        class = "card-img-top image-fluid">
    {% else %}
        <img src="https://picsum.photos/200/300" alt="random-image-{{ forloop.counter }}"
        class = "card-img-top image-fluid">
    {% endif %}
    </a>
    <div class="card-body">
        <i class="fa-2x {{ posting.icon }}"></i>
        {{ posting.content }}              
    </div>
</article>

06_django_advanced/03_image_upload/sns/templates/sns/_comment.html
<div class="col-12 col-md-6">
    <div class="card mb-2">
        <div class="card-body">
        <form action="{% url 'sns:create_comment' posting.id %}" method="POST">
            {% csrf_token %}
            <label for="comment">{{ request.user }} leave your comment</label>
            <input type="text" name="content" id="commnet" class="form-control" autofocus>
            <input type="submit" value="OK">
        </form>
        </div>
    </div>

    <div class="card">
        <ul class="list-group list-group-flush">
            {% if comments %}
                {% for comment in comments %}
                    <li class="list-group-item mb-1"> {{ comment.user }}: {{ comment.content }} <a href="{% url 'sns:delete_comment' posting.id comment.id %}"><i class="fas fa-trash"></i></a></li>
                {% endfor %}
            {% else %}
                <li class="list-group-item mb-1">No Comment</li>
            {% endif %}
        </ul>
    </div>
</div>

06_django_advanced/03_image_upload/sns/templates/sns/_header.html
<header class="mt-4 mb-4">
    <form action="{% url 'sns:create_posting' %}" enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        <div class="form-row align-items-center">
            <!--icon select part-->
            <div class="col-auto my-1">
                <label for="icon" class="sr-only">icon</label>
                <select name="icon" id="icon" class="custom-select mr-sm-2">
                    <option value="far fa-question">?</option>
                    <option value="far fa-smile">:)</option>
                    <option value="far fa-angry">:(</option>
                    <option value="far fa-smile-wink">;)</option>
                    <option value="far fa-angrycreative">flex</option>
                </select>
            </div>

            <!-- content input tag-->
            <div class="col-sm-6 my-1">
                <label for="content" class="sr-only">content</label>
                <input type="text" name="content" id="content" class="form-control" placeholder="feels like...">
            </div>

            
            <!-- image file input tag-->
            <div class="col-sm-4 my-1 input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Upload</span>
                </div>
                <div class="custom-file">
                    <input type="file" name="image" id="image" accept="image/*" class="custom-file-input" placeholder="Choose image">
                    <label for="image" class="custome-file-label">Browse</label>
                </div>
            </div>

            <!-- image file input tag-->
            <div class="col-auto my-1">
                <button type="submit" class="btn btn-primary">submit</button>
            </div>
        </div>
    </form>
</header>

06_django_advanced/03_image_upload/sns/templates/sns/_navbar.html
<nav class="mb-3">
    <ul class="nav nav-tabs">
        <li class="nav-item">
            <a href="{% url 'sns:posting_list' %}" class="nav-link {% block list %}
            {% endblock list %}">SNS</a>
        </li>
        <li class="nav-item">
            <a class="nav-link {% block detail %}
            {% endblock detail %}" area-disabled="true">Detail</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
            <a href="{% url 'accounts:logout'%}" class="nav-link">Log Out</a>
        </li>
        <li class="nav-item">
            <a href="#" class="nav-link">{{ user.username }}</a>
        </li>
        {% else %}
        <li class="nav-item">
            <a href="{% url 'accounts:signup'%}" class="nav-link">Sign Up</a>
        </li>
        <li class="nav-item">
            <a href="{% url 'accounts:login'%}" class="nav-link">Log In</a>
        </li>
        {% endif %}
    </ul>
</nav>

06_django_advanced/03_image_upload/sns/templates/sns/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Bootstrap CSS-->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!--FontAwesome icon set-->
    <script src="https://kit.fontawesome.com/a797bec1bc.js" crossorigin="anonymous"></script>
    <title>{% block title %}
    {% endblock title %}</title>
</head>
<body>
    <div class="container">
    {% block body %}
    {% endblock body %}
    </div>
    <!-- Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

06_django_advanced/03_image_upload/sns/templates/sns/posting_detail.html
{% extends 'sns/base.html' %}

{% block title %}

{% endblock title %}

{% block detail %}
active
{% endblock detail %}

{% block body %}
    <div class="row mt-3">
        <div class="col-12 col-md-6">
            <div class="card">
                {% if posting.image %}
                    <img class="card-img-top image-fluid" src="{{ posting.image.url }}" alt="{{ posting.image }}">
                {% else %}
                    <img class="card-img-top image-fluid" src="https://picsum.photos/500/300" alt="random">
                {% endif %}
                <div class="card-body">
                    <div class="row">
                        <div class="col-2">
                            <i class=" {{ posting.icon }} fa-2x"></i>
                        </div>
                        <div class="col-5">
                            {{ posting.like_users.count }}명이 좋아합니다.
                        </div>
                        <div class="col-2">
                            <form action="{% url 'sns:toggle_like' posting.id %}" method="POST">
                                {% csrf_token %}
                                <button>
                                {% if is_like %}
                                    Like
                                {% else %}
                                    Dislike
                                {% endif %}
                                </button>
                            </form>
                        </div>
                    </div>
                    <hr>
                    <div class="row">
                        <div class="col-10">
                            <p class="card-text">{{ posting.user }}</p>
                            <p class="card-text">{{ posting.content }}</p>
                        </div>
                        <div class="col-2">
                        {% if user == posting.user %}
                            <form action="{% url 'sns:delete_posting' posting.id %}" method="post">
                                {% csrf_token %}
                                <button><i class="fas fa-trash"></i></button>
                            </form>
                        {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% include 'sns/_comment.html' %}
    </div>
{% endblock body %}

06_django_advanced/03_image_upload/sns/templates/sns/posting_list.html
{% extends 'sns/base.html' %}

{% block title %}

{% endblock title %}

{% block list %}
active
{% endblock list %}

{% block body %}
    {% if user.is_authenticated %}
    {% include 'sns/_header.html' %}
    {% endif %}
    {% if postings %}
        <section class="card-columns">
        {% for posting in postings %}
            {% include 'sns/_card.html' %}
        {% endfor %}
        </section>
    {% endif %}
{% endblock body %}